### ISSUE TITLE
paper attribution

### ISSUE THREAD

**Issue by weiyifanfan** [ibalazevic/TuckER#10]
I want to ask if your paper was published in journals or conferences.

**Comment by ibalazevic** [comment]
The short version of the paper has been published at the [ICML Adaptive & Multitask Learning Workshop](https://www.amtl-workshop.org/accepted-papers): https://openreview.net/pdf?id=BkgREcHjnE. The long version is currently under review.

**Comment by ibalazevic** [comment]
Update: the long version will appear at EMNLP 2019!
