### ISSUE TITLE
Hyperparameters for Yago3-10

### ISSUE THREAD

**Issue by AndRossi** [ibalazevic/TuckER#14]
Hi, thanks for developing this amazing model.
I'd like to try and train it on the Yago3-10 dataset (I think you have used it in your other work titled "Hypernetwork Knowledge Graph Embeddings").

Have you ever tried to train TuckER on that dataset? 
Can you suggest me any hyperparameter settings, before I start running a long grid search? :)

Thanks for your help!

Andrea

**Comment by ibalazevic** [comment]
Hi, sorry but I haven't actually run TuckER on Yago. I would maybe look at hyperparameters used on other datasets as a starting point.

**Comment by AndRossi** [comment]
Ok, nevermind. As you suggest, I'll start with the hyperparameters used on the other datasets.
Have a nice day!
