### ISSUE TITLE
Relation Prediction

### ISSUE THREAD

**Issue by Demirrr** [ibalazevic/TuckER#16]
Dear Ivana,

firstly thank you for the work and clean implementation. As I am interesting in relation prediction via TuckER, I was wondering whether you could provide a function like `def forward_rel(self, e1_idx, e2_id):` so that one could make use of TuckEr in relation prediction task.

Cheers

**Comment by ibalazevic** [comment]
Dear Demir,

Thanks, glad you've found the code helpful! 

Unfortunately, I don't have time currently to make any substantial changes to the code. That said, feel free to do it and create a pull request. One potential issue I see with doing relation prediction is that one might lose the speed-up benefit of 1-N scoring, given that a typical knowledge graph contains many more entities than relations.

Cheers,
Ivana
