### ISSUE TITLE
Do you only test tails in the evalution? 

### ISSUE THREAD

**Issue by liu-jc** [ibalazevic/TuckER#18]
I am a bit confused about the evaluation protocol. In the evaluation, you only feed (head, rel) to the model and get predictions with n elements representing the scores of (head, rel, t_1) ... (head, rel, t_n). Why you don't repeat this process for the tail? Could you explain the reason? I think it should be done right? Previous works all conduct the evaluation in this way. 
Maybe I misunderstand your code. Look forward to your reply.

**Comment by ibalazevic** [comment]
Please see this [issue](https://github.com/ibalazevic/TuckER/issues/1) for the answer to your question.
