### ISSUE TITLE
Could the one-way evaluation be a problem?

### ISSUE THREAD

**Issue by Xiaobeing** [ibalazevic/TuckER#19]
Hi,

I have a question on the evaluation in the code.

when the test rank is evaluated, the scores seem only be calculated for each head toward all tails.  I didn't see the scores are calculated for each tail toward all heads in the code.  Don't people usually calculate them both and average them as the final scores? Would this one-way evaluation be a problem, such as having some bias?

Thank you!

**Comment by YancaoZhang** [comment]
Same question as above.

**Comment by YancaoZhang** [comment]
When loading data, `reverse=True`.

**Comment by ibalazevic** [comment]
Please see this [issue](https://github.com/ibalazevic/TuckER/issues/1) for the answer to your question.
