### ISSUE TITLE
What different from torch==0.4.0 to torch==1.0.0?

### ISSUE THREAD

**Issue by l6270789** [ibalazevic/TuckER#8]
I used torch==1.0.0 and cannot reproduce the results in the paper. What different from torch==0.4.0 to torch==1.0.0? Thanks for your help!

**Comment by ibalazevic** [comment]
Sorry, not sure I can help with this right now. I'm planning to upgrade to 1.0.0 soon, but until I do, maybe try downgrading to 0.4.0 and reproducing the results there.
